JFMServices_sources = [
'./utils.cpp',
'./Fitting/PreFitter.cpp',
'./Fitting/JFMFitter.cpp',
'./Fitting/JFMFitting.cpp',
'./Test.cpp',
'./MonteCarlo/JFMMonteCarlo.cpp',
'./MonteCarlo/MonteCarloEngine.cpp',
'./DataManegement/Dumper.cpp',
'./DataManegement/DataManager.cpp',
'./DataManegement/Loader.cpp',
'./DataManegement/IDataManager.cpp',
'./Models/JFMAdditionalParameters.cpp',
'./Models/JFMErrorModel.cpp',
'./Models/JFMModels.cpp',
'./Models/CalculateData.cpp',
'./Calculator/CalculatorGpu.cpp',
'./Calculator/CalculatorCpu.cpp',
]

JFMServices_includes = [
    'DataManegement',
    'Fitting',
    'Models',
    'MonteCarlo',
    './'
]
