JFMApp_sources = [
    './DataGenerator.cpp',
    './App/AppRunner.cpp',
    './App/App.cpp',
    './DataStorage/UIState.cpp',
    './DataStorage/NumericsConfig.cpp',
    './DataStorage/ViewData.cpp',
    './DataStorage/BrowserData.cpp',
    './DataStorage/Characteristic.cpp',
    './DataStorage/PlotData.cpp',
    './Platform/window.cpp',
    './UI/Views/FileSelector.cpp',
    './UI/Views/global_ds.cpp',
    './UI/Views/CharacteristicInspector.cpp',
    './UI/Views/MonteCarloInspector.cpp',
    './UI/Views/CharacteristicList.cpp',
    './UI/Views/BrowserArea.cpp',
    './UI/Views/PlotArea.cpp',
    './UI/Views/ArrheniusViewer.cpp',
    './UI/Views/ViewMenu.cpp',
    './UI/Config/global.cpp',
]

JFMApp_includes = [
    'Platform',
    'UI/Config',
    'UI/Views',
    'UI',
    'DataStorage',
    'App',
    './'
]
